---
title: "Cartola Siafi Futebol Clube:"
subtitle: "comparação entre receita e despesa dos clubes e dos órgão federais"
output:
  html_document:
    code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
options(digits = 2)
```


```{r, message=FALSE}
library(dplyr)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(ggrepel)
library(DT)
```



```{r}
clubes <- read_excel("clubes.xlsx")
```


```{r}
clubes<- clubes%>%
  mutate (despesa = receita - resultado)%>%
  mutate (absoluto = abs(resultado))%>%
  mutate (tag = if_else(rank(-absoluto) > 5,   "", clube)  )%>%
  mutate (grupo = "cbf")%>%
  mutate(forma = 19)%>%
  mutate (cor_ponto = case_when(
                  resultado > 0 ~ "positivo",
                  resultado == 0 ~ "nulo",
                  resultado < 0 ~ "negativo" ))
```

[https://vuorre.netlify.com/post/2017/01/04/how-to-create-within-subject-scatter-plots-in-r-with-ggplot2/]


```{r}


lims_clube <- c(0, max(c(max(clubes$despesa),max(clubes$receita))))

p_clubes <-  ggplot (clubes) +
  geom_point(aes (shape = forma, x = despesa, y = receita,
                  color =  cor_ponto,
                  alpha = 0.3,
                  size = absoluto,
                  label = clube))+
  scale_color_manual("resultado", values = c("positivo" = "blue", "nulo" = "gray", "negativo" = "red"))+
  geom_text(aes ( x = despesa, y = receita, label = clube))+
    scale_shape_identity()+
    geom_abline(alpha = 0.2) +
    scale_x_continuous("Despesa", limits = lims_clube) +
    scale_y_continuous("Receita", limits = lims_clube) +
    theme_minimal()
(p_clubes <- ggplotly(p_clubes))%>%
  layout(showlegend = FALSE)
  




```

```{r}
gov <- read_excel("org.xlsx")

colnames(gov)<- c("poder_cod","poder","org_max_cod","org_max","org_sup_cod","org_sup", "org_cod","org","uf","uf_nome","muni_cod","muni","ug_cod","ug","despesa","receita","resultado")

gov<-gov%>% mutate (grupo = "gov")%>%
  mutate(forma = 2 )%>%
  mutate (absoluto = abs(resultado))%>%
  mutate (cor_ponto = case_when(
                  resultado > 0 ~ "positivo",
                  resultado == 0 ~ "nulo",
                  resultado < 0 ~ "negativo" ))

gov$receita <- round(gov$receita/1000000,1)
gov$despesa <- round(gov$despesa/1000000,1)
gov$resultado <- round(gov$resultado/1000000,1)





```


```{r}

gov%>% group_by(org_max, org_max_cod)%>%
  summarise( count = n())%>%
  arrange(desc(count))





datatable(gov%>%  select(poder,org_max,org,uf,ug,ug_cod, receita, despesa, resultado),
          filter = 'top', options = list(  pageLength = 5, autoWidth = TRUE, style = "default", width = 1200))

p_org<- gov%>%
  group_by(org_max)%>%
  summarise( count = n())%>%
  ggplot+
  geom_col(aes(y = count, x = reorder (org_max, count)))+
  coord_flip()



(p_org <- ggplotly(p_org))






```

```{r}

lim_gov <- gov %>%
  filter ( org_max_cod != "01000")%>%
  mutate (absoluto = abs(resultado))%>%
  mutate (tag = if_else(rank(-absoluto) > 5,   "", ug_cod)  )


lims_gov <- c(0, max(c(max(lim_gov$despesa),max(lim_gov$receita))))

#lim_gov$tag <- gsub(" ", "\n", lim_gov$tag)
#levels(lim_gov$ug) <- gsub(" ", "\n", levels(lim_gov$ug))


p_gov <-   ggplot (lim_gov) +
  geom_point(aes ( shape = forma, x = despesa, y = receita, color = cor_ponto,size = absoluto, label = ug, alpha = 0.5))+
  geom_text(aes ( x = despesa, y = receita, label = tag))+
  scale_color_manual("resultado", values = c("positivo" = "blue", "nulo" = "gray", "negativo" = "red"))+
    scale_shape_identity()+
    geom_abline( alpha = 0.3) +
    scale_x_continuous("Despesa", limits = lims_gov) +
    scale_y_continuous("Receita", limits = lims_gov) +
    theme_minimal()

 
  
(p_gov <- ggplotly(p_gov) )%>%
  layout(showlegend = FALSE)





```



```{r}

gov_s<-gov

clube_join<- clubes%>%
  select(clube, uf,receita, despesa, resultado, absoluto, tag, grupo, forma, cor_ponto)%>%
  mutate(tam = absoluto/10)


colnames(clube_join)[1]<-"nome" 


gov_join<- gov_s%>%
  select(ug_cod,uf,receita, despesa, resultado, absoluto, grupo, forma, cor_ponto)%>%
  mutate(tam = 1)%>%
  mutate (tag = if_else(rank(-absoluto) > 5,   "", ug_cod)  )

colnames(gov_join)[1]<-"nome" 

cartola <- full_join(clube_join,gov_join)

```


```{r}


lims_cartola <- c(0, max(c(max(cartola$despesa),max(cartola$receita))))

#lim_gov$tag <- gsub(" ", "\n", lim_gov$tag)
#levels(lim_gov$ug) <- gsub(" ", "\n", levels(lim_gov$ug))



p_cartola <-   ggplot (cartola) +
  geom_point(aes ( shape = forma, x = despesa, y = receita, color = cor_ponto,size = tam, label = nome, alpha = 0.3))+
  geom_text(aes ( x = despesa, y = receita, label = tag))+
  scale_color_manual("resultado", values = c("positivo" = "blue", "nulo" = "gray", "negativo" = "red"))+
    scale_shape_identity()+
    geom_abline( alpha = 0.3) +
    scale_x_continuous("Despesa", limits = lims_cartola ) +
    scale_y_continuous("Receita", limits = lims_cartola ) +
    theme_minimal()

 
  
(p_cartola <- ggplotly(p_cartola) )%>%
  layout(showlegend = FALSE)

```

