---
title: "Cartola 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    runtime: shiny
    social: ["twitter", "facebook", "menu"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(flexdashboard)
library(knitr)
library(shiny)
```



```{r}
clubes <- read_excel("clubes.xlsx")


clubes<- clubes%>%
  mutate (despesa = receita - resultado)%>%
  mutate (absoluto = abs(resultado))%>%
  mutate (grupo = "cbf")

gov <- read_excel("org.xlsx")

colnames(gov)<- c("poder_cod","poder","org_max_cod","org_max","org_sup_cod","org_sup", "org_cod","org","uf","uf_nome","muni_cod","muni","ug_cod","tag","despesa","receita","resultado")



gov$receita <- round(gov$receita/1000000,1)
gov$despesa <- round(gov$despesa/1000000,1)
gov$resultado <- round(gov$resultado/1000000,1)

gov<-gov%>% 
  mutate (absoluto = abs(resultado))

clube_join<- clubes%>%
  select(clube, uf,receita, despesa, resultado, absoluto)%>%
  mutate (org = "cbf")%>%
  mutate (tag = clube)%>%
  mutate (cor_ponto = case_when(
    resultado > 0 ~ "positivo",
    resultado == 0 ~ "nulo",
    resultado < 0 ~ "negativo"))%>%
    mutate (cor_texto = "black")


colnames(clube_join)[1]<-"nome" 


gov_join<- gov%>%
  select(ug_cod,uf,receita, despesa, resultado, absoluto, org, tag)%>%
  mutate (cor_ponto = case_when(
    resultado > 0 ~ "positivo",
    resultado == 0 ~ "nulo",
    resultado < 0 ~ "negativo"))%>%
    mutate (cor_texto = "green")

gov_join$tag <- gsub(" ", "\n", gov_join$tag)
levels(gov_join$tag) <- gsub(" ", "\n", levels(gov_join$tag))
  

colnames(gov_join)[1]<-"nome" 


cartola<- full_join(gov_join, clube_join)



```

Selecione o período {.sidebar}
========================


###### 

```{r}
selectizeInput("nome", "Escolha a UG", unique (gov_join$nome), selected = "170166", multiple = FALSE,
               options = NULL)
```




UG x Clubes
========================

Column {data-width=1000}
-----------------------------------------------------------------------

### Campeonato de 2018: UG x Clubes (R$ milhão)

```{r}


renderPlotly({

  

  
cartola_s<- cartola %>% filter (nome == input$nome | org == "cbf")

  
lims_cartola <- c(0, max(c(max(cartola_s$despesa),max(cartola_s$receita))))

p_cartola <-   ggplot (cartola_s) +
  geom_point(aes ( x = despesa, y = receita,
    color =  cor_ponto,
    size = absoluto, label = tag))+
    scale_shape_identity()+
  geom_text(aes ( x = despesa, y = receita, label = tag, color = cor_texto))+
  scale_color_manual("resultado", values = c("positivo" = "blue", "nulo" = "gray", "negativo" = "red", "black" = "black", "green" = "green"))+
  geom_abline(alpha = 0.3) +
    scale_x_continuous("Despesa", limits = lims_cartola ) +
    scale_y_continuous("Receita", limits = lims_cartola ) +
    theme_minimal()

 
  
(p_cartola <- ggplotly(p_cartola) )%>%
  layout(showlegend = FALSE)
  

})

 

```







### Comparativo 2018 (R$ milhão) {data-width=220}


```{r}

renderDT({

gov_join_s <- gov_join %>% filter(nome == input$nome)
  
cartola_s<- full_join(gov_join_s, clube_join)

datatable(cartola_s%>%  select(nome, receita, despesa, resultado),
          filter = 'top', options = list(  pageLength = 25, autoWidth = TRUE, style = "default", width = 300))
})
```



Ranking Geral
========================

### Ranking Geral 2018 (R$ milhão)

```{r}
renderDT({


  


datatable(cartola%>%  select(nome,org, uf, receita, despesa, resultado),
          filter = 'top', options = list(  pageLength = 25, autoWidth = TRUE, style = "default", width = 1200))
})
```

